name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r Files/requirements.txt

    - name: Stash any local changes
      run: git stash

    - name: Pull latest changes
      run: git pull origin main 

    - name: Run Config script
      run: python Files/app.py 

    - name: Run Warp script
      run: python Files/warp.py

    - name: Run Splitter script
      run: python Files/sort.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions"
        author_email: "actions@github.com"
        message: "Updated 9 minutes Ago ⚡"
        add: "."  
        push: true  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
